### ISSUE TITLE
Mobs can blow up hyperloop tubes.

### ISSUE THREAD

**Issue by falsechicken** [joe7575/Minetest-Hyperloop#10]
It seems that the mobs from the mobs_redo mod can break hyperloop tubes and probably elevator shafts. The Dungeon Master mob shoots a fireball that explodes and we had it destroy hyperloop tubes on our server with the explosion. 

The explosion seems to originate from this code: https://notabug.org/TenPlus1/mobs_redo/src/master/api.lua#L4259

**Comment by joe7575** [comment]
Should be fixed
