### ISSUE TITLE
Remove stations

### ISSUE THREAD

**Issue by xenonca** [joe7575/Minetest-Hyperloop#7]
After looking into the README and Wiki I unfortunately haven't been able to find information on how to remove a stations that has been built. After manually (using WorldEdit to remove the station block) removing the physical station it still appeared in the Hyperloop Station Book.

**Comment by joe7575** [comment]
WorldEdit is always a bad idea :)
You build the station with the "Build Station" button. And you also destroy the station with the "Destroy Station" button.  That means, you will get all your items back.

**Comment by xenonca** [comment]
Thank you! I thought I've looked at it already, obviously not close enough :P
