### ISSUE TITLE
Graphical glitches?

### ISSUE THREAD

**Issue by AmyMoriyama** [joe7575/Minetest-Hyperloop#9]
So, was testing this mod on my server and there is a strange graphical glitch. When inside the pod, if you move around, the text on the screen glitches. Screenshots attached.

![screenshot_20220801_210046](https://user-images.githubusercontent.com/87048190/182269790-4d2efced-52fc-44bb-bc10-a133e540dec5.png)

![screenshot_20220801_210051](https://user-images.githubusercontent.com/87048190/182269816-09b99e11-0ee0-4ac9-a5f9-18cb1342fa4c.png)

![screenshot_20220801_210053](https://user-images.githubusercontent.com/87048190/182269837-3c376c56-69cf-4041-83b7-d8fe29f2f3f6.png)

**Comment by joe7575** [comment]
I have changed the display settings. So, give it a try.

**Comment by AmyMoriyama** [comment]
Excellent, the glitches are gone. Thank you.
